Feat/clear filter button
deco-sites/persono pull request #116
Opened 2024-04-18 03:12 UTC by viniciusventura29

2024-04-18 18:45 UTC, aka-sacci requested changes

2024-04-18 18:45 UTC, aka-sacci commented on components/search/Filters.tsx
> +    .filter((item) => item.slugs.length > 0);
usar um filter depois de um reduce é ruim! da pra filtrar diretamente no reduce. Isso evita que o array seja iterado duas vezes!

2024-04-18 18:45 UTC, aka-sacci commented on components/search/Filters.tsx
> +    const tempArray = [...rawFiltersToApply];
const tempArray = rawFiltersToApply

2024-04-18 18:45 UTC, aka-sacci commented on components/search/Filters.tsx
> +  if (clearFilter.value == true) {
===

2024-04-19 20:45 UTC, viniciusventura29 commented on components/search/ActiveFilterTag.tsx
> +function clearFilters({ basePath }: { basePath: string | undefined }) {
fixed

2024-04-19 20:45 UTC, viniciusventura29 commented on components/search/Filters.tsx
> +    .filter((item) => item.slugs.length > 0);
fixed

2024-04-19 20:45 UTC, viniciusventura29 commented on components/search/Filters.tsx
> +    const tempArray = [...rawFiltersToApply];
fixed

2024-04-19 20:45 UTC, viniciusventura29 commented on components/search/Filters.tsx
> +  if (clearFilter.value == true) {
fixed

2024-04-19 23:55 UTC, aka-sacci approved these changes

2024-04-19 23:55 UTC, merged