Fix/size guide modal mobile
deco-sites/persono pull request #120
Opened 2024-04-28 03:56 UTC by viniciusventura29

2024-04-30 14:34 UTC, aka-sacci-ccr requested changes

2024-04-30 14:34 UTC, aka-sacci-ccr commented on components/product/SizesGuideModal.tsx
> +            {pijamaSizes.length > 0
Como o pijamaSizes nao vai mais existir, a lógica desse componente vai mudar. Mas é bom se atentar a:

> Excesso de `devices === 'desktop'` -> armazena esse bool em uma variável e usa sempre que vc precisar

> encadeamento de ifs -> cara, isso deixou o código muito confuso. Há soluções melhores, tipo criar um objeto que armazene múltiplos resultados que você precisa, tipo:

const a = {
    "desktop": "val1",
    "mobile": "val2",
    "tablet": "val3"
  }

ai, voce consegue acessar usando `a.[device]`. Mantenha esse tipo de exemplo nas próximas vezes que tu for fazer encadeamento de IFs,

2024-05-07 13:23 UTC, carcara-gustavo requested changes

2024-05-07 13:23 UTC, carcara-gustavo commented on components/product/SizesGuideModal.tsx
> +  } else {
n precisa de else

2024-05-07 13:23 UTC, carcara-gustavo commented on components/product/SizesGuideModal.tsx
> +              ✕
Existe o icon XMark

2024-05-07 13:23 UTC, carcara-gustavo commented on components/product/SizesGuideModal.tsx
> +            <div class="flex py-4 text-base justify-between">
podia ter feito uma ul/li

2024-05-07 13:23 UTC, carcara-gustavo commented on components/product/SizesGuideModal.tsx
> +        >
Verifica o componente Modal. role dialog quebra no iOS

2024-05-07 13:25 UTC, carcara-gustavo commented on components/product/ProductSizeVariantSelector.tsx
Cria um componente para o Guia de tamanhos e transforma apenas ele em uma ilha e envie apenas as Props que são realmente necessárias, não tem necessidade de criar esse componente inteiro como ilha. **Componentize as coisas**

2024-05-12 22:32 UTC, merged